[package]
name = "pin-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.135"

[build-dependencies]
cxx-build = "1.0.135"
flate2 = "1.0.35"
reqwest = { version = "0.12.9", features = ["blocking", "rustls-tls"] }
tar = "0.4.43"
